---
- name: Converge
  hosts: all
  tasks:
    - name: Testing nierdz.nextcloud
      ansible.builtin.include_role:
        name: nierdz.nextcloud
        tasks_from: main.yml
  vars:
    nextcloud_domain: "nextcloud.local"
    nextcloud_admin_user: "admin"
    nextcloud_admin_password: "notsecurepassword"
    nextcloud_instanceid: "somerandomshit"
    nextcloud_passwordsalt: "notsecurepasswordsalt"
    nextcloud_secret: "notsecuresecret"
    nextcloud_dbpassword: "notsecurepassword"
    nextcloud_apps:
      - tasks
